platform:
  - x64

os:
  - Visual Studio 2015

install:
  - ps: Install-Product node 14 x64
  - curl -L -o nasm.exe https://www.nasm.us/pub/nasm/releasebuilds/2.13.03/win64/nasm-2.13.03-installer-x64.exe 
  - start /wait nasm.exe /S 
  - ps: $env:path="C:\Program Files\nasm;$($env:path)" 
  - sed -i "s@git\@github.com:@https:\/\/github.com\/@" .gitmodules
  - git submodule update --init --recursive
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
  # Artifacts are packaged before before_deploy
  - bash scripts\package.sh

artifacts:
  - path: 'build\*\*.zip'
    name: 'deepstream.io-release'

  - path: '**\*.zip'

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release description'
    auth_token: ${GITHUB_TOKEN}
    draft: false
    force_update: true
    artifact: 'deepstream.io-release'
    on:
      appveyor_repo_tag: true

build: off
